### PR TITLE
Add a new exception type

### PR DESCRIPTION
**Pull request by speich**
Adds a new exception class required for the HTMLTableElement. It also adds phpdoc to the base class DOMomException.

Was not sure how to go about the read-only property "name".

### CODE REVIEW

**Comment by g105b** [comment]
Hi @speich ,

Please see how I've added the `MagicProp` trait to the base `DOMException`, so it can use property getter and setter functions. This concept is used throughout the DOM because of the expectation of having either read-only properties, or "live" properties that update according to the state of the live document.

Thanks for your efforts on this so far, let me know if you have any other questions about contributing and I'll see if I can improve the documentation for other contributors.

Greg.

**Comment by g105b** [comment]
Thanks again for your contribution.

**Comment by speich** [comment]
How should I/we go about specific error messages when setting a property ? For example when setting the HTMLTableCaption property, the specs say to throw a HierarchyRequestError error. But since the method `protected function __prop_set_caption(?HTMLTableCaptionElement $value): void {}` does a type check, a TypeError is thrown by php before I can even test for the type and throw the custom HierarchyRequestError

**Comment by speich** [comment]
What about relaxing the method argument type to HTMLElement and then test for the correct type inside the method?

**Comment by emileward** [comment]
This is a good question. It's something that hasn't been decided yet so
it's a good opportunity to debate it.

Personally, I think that if we've got a type system in the language, we
should utilise it because it will only make things clearer for the
developer using it. If there can only ever be an HTMLTableCaptionElement as
a valid type, my vote is to allow PHP to enforce this, otherwise we're only
reimplementing the functionality of a type check.

That would mean we have less to implement as a lot of exceptions could be
ignored.

I'm interested to hear your views on the best approach.

Greg.

**Comment by g105b** [comment]
Hi @speich,

This is a good question. It's something that hasn't been decided yet so it's a good opportunity to debate it.

Personally, I think that if we've got a type system in the language, we should utilise it because it will only make things clearer for the developer using it. If there can only ever be an HTMLTableCaptionElement as a valid type, my vote is to allow PHP to enforce this, otherwise we're only reimplementing the functionality of a type check.

That would mean we have less to implement as a lot of exceptions could be ignored.

Also, we could easily change the type to `mixed`, but then the type hints in editors wouldn't be as useful.

I'm interested to hear your views on the best approach, and your feedback on the above.

Greg.

**Comment by speich** [comment]
I agree with what you say. It certainly would make the code shorter, easier to read and maintain if we used php's type system.

The only two things we would loose, are the faithfulness to the spec and the information content of the error, which is slightly different. The former just tells me that I used the wrong type, the latter tells my that I can't insert my node into the DOM at this parent. But I don't think that difference is really relevant, or is it?

And anyway, we can still change this at a later time, by just changing the passed types and adding the error checks, if we wanted to be closer to the spec (for the sake of it).

BTW, I'm really impressed with your facade. It's a pleasure to work with and I will open a PR for the HTMLTableElement including Tests soon.

Simon

**Comment by g105b** [comment]
That's really great to hear. Looking forward to it. I'll get many of the other elements implemented alongside.

**Comment by g105b** [comment]
Just FYI @speich, I've started implementing some HTMLElements this morning. I'll push through while my coffee's still hot, but later I have to pick up client work.

In the process of starting with HTMLAnchorElement, I created a new TestCase class that can be used to automate the repetitive task of asserting that the attribute:property relationship is correct. For example, the HTMLAnchorElement has a `hreflang` property that directly relates to the value of the `hreflang` HTML attribute... I'm predicting there will be many getters/setters like this, so please check out the [HTMLElementTestCase](https://github.com/PhpGt/Dom/blob/facade/test/phpunit/HTMLElement/HTMLElementTest.php) and [the first unit tests for HTMLAnchorElement](https://github.com/PhpGt/Dom/blob/facade/test/phpunit/HTMLElement/HTMLAnchorElementTest.php).

**Comment by speich** [comment]
ok, thanks for the tip, ill check it out

**Pull request merged**
