### PR TITLE
Implement the HTMLTableElement

### PR DESCRIPTION
**Pull request by speich**
That was a beast. I hope I implemented everything according to the spec

### CODE REVIEW

**Comment by g105b** [comment]
Hey @speich, thanks so much for your contribution. This looks great - a big piece of functionality with some good tests. I'll checkout on my computer later and run the tests and do some debugging. We're getting there with the final HTMLElements!

**Comment by speich** [comment]
I just started to implement the HTMLTableColElement which has the attribute span. Its value is required to be a non-negative integer clamped to [1, 1000] 
The spec lists rules for parsing different data types https://html.spec.whatwg.org/multipage/common-microsyntaxes.html#rules-for-parsing-non-negative-integers

Is there already a class in the facade, that already implements these rules and that I can use ?  If not, what do suggest I'll do ?

**Comment by g105b** [comment]
There isn't already anything that validates attributes. If this is a common requirement, we could add something to reuse, but for now I think the simplest solution is to use PHP's type system as far as possible (enforcing an integer), then throw the relevant exception if the variable is `< 1 || > 1_000`.

This is likely to be something that would be useful to abstract into some reusable functionality, but until we come to need it being reused, I think it makes most sense to implement in-place, if you agree.

**Comment by speich** [comment]
ok, i'll implement in-place for now

**Comment by g105b** [comment]
I've decided to set my IDE to display PHPStan level 6 warnings by default. It's overkill, but it helps me better understand what the code's doing, which I suppose is exactly the point.

I went through and added extra type hint comments where necessary to suppress PHPStan's warnings, and in the process it allowed me to understand what the tests and functionality is doing in your branch.

Thanks for your work on this. I'll spend a little bit more time reading through it and merge it later if I don't have any questions.

**Comment by g105b** [comment]
Thanks again @speich . One thing I'm looking into that you might be able to help complete is two lines of untested functionality:

https://github.com/PhpGt/Dom/blob/5f478883175a674c525ff6d4f4709500706cc5e5/src/HTMLElement/HTMLTableElement.php#L311

and 

https://github.com/PhpGt/Dom/blob/5f478883175a674c525ff6d4f4709500706cc5e5/src/HTMLElement/HTMLTableElement.php#L445

I'm taking a look if I can create some unit tests to test these lines, but I think they might actually be obsolete and never end up being executed. 

Will report back if I find anything.

**Comment by speich** [comment]
Good catch!
https://github.com/PhpGt/Dom/blob/5f478883175a674c525ff6d4f4709500706cc5e5/src/HTMLElement/HTMLTableElement.php#L310-L312
The idea was to filter out rows of tables inside the table and that are direct children of the table (don't have a tbody as parent). But this is already taken care of by (I don't need to compare table with table, null will do too)
https://github.com/PhpGt/Dom/blob/5f478883175a674c525ff6d4f4709500706cc5e5/src/HTMLElement/HTMLTableElement.php#L313-L315

Also the test
https://github.com/PhpGt/Dom/blob/5f478883175a674c525ff6d4f4709500706cc5e5/test/phpunit/HTMLElement/HTMLTableElementTest.php#L381-L396
never creates a tr that is an immediate child of the table, because insertRow() automatically inserts a tbody first. Test should be modified accordingly to create a tr directly and append it.

https://github.com/PhpGt/Dom/blob/5f478883175a674c525ff6d4f4709500706cc5e5/src/HTMLElement/HTMLTableElement.php#L444-L446
I added this probably for completeness, but as you spotted, it is never used.

**Comment by g105b** [comment]
Thanks for the explanation. It's all very readable in code too. I'll make any adjustments while I go through some more HTMLElement classes and get closer to full implementation.

**Comment by g105b** [comment]
Follow-on PR: #273

**Pull request merged**
