### PR TITLE
HTMLDocument test bug fix.

### PR DESCRIPTION
**Pull request by aguimaraes**
Just a little mistake in HTMLDocument tests.

### CODE REVIEW

**Comment by g105b** [comment]
Do you think method chaining would be a useful addition? I never use that particular programming style, but I see it's quite popular.

**Comment by aguimaraes** [comment]
I'm used to declarative programming because I usually learn from Adam Wathan and the Laravel universe.

Programming like this makes method chaining mandatory and judging by the success of his last book about the subject, we should provide that feature.

Some context:

http://adamwathan.me/2016/05/19/refactoring-with-collections-and-null-objects/

http://adamwathan.me/refactoring-to-collections/

**Comment by g105b** [comment]
I'll read over the articles you provided. Something we should consider is to not break the way the DOM standard currently works. Maybe a wrapper object (jquery style, dare I say it) would be good for this?

**Comment by aguimaraes** [comment]
I would use it without concerns, but I never saw that elsewhere in PHP.

Do you know about projects using that solution?

**Comment by g105b** [comment]
All I'm saying is that the DOM currently does not support method chaining. To support method chaining, all methods need to return their `$this` reference, which is not how the DOM currently behaves.

An idea is to enable this behaviour, something like `$document->enableChaining();` which will set a flag to return `$this` rather than the standard return type.

I don't really like this idea, because then it loses the benefits of strict return types, so I'll give it some thought and create a new ticket when I have any idea. Feel free to raise a new issue if you have an idea of how this can be implemented.

Thanks.

**Pull request merged**
