### PR TITLE
Test that property innerHTML is set

### PR DESCRIPTION
**Pull request by speich**
Tests that the innerHTML property on the DocumentFragment is set

### CODE REVIEW

**Comment by g105b** [comment]
Thanks for adding the test for this. Thinking about it, maybe the last line would not make sense - once a fragment is added to the document, the reference to the fragment should be discarded, but if we still retain a reference the innerHTML should not be reset. What do you think to this?

**Comment by speich** [comment]
From [DocumentFragment](https://developer.mozilla.org/en-US/docs/Web/API/DocumentFragment#Usage_notes) I understood that after moving the fragment's nodes into the DOM, an empty DocumentFragment is left. So I guess I should test that innerHTML is empty instead of null?

**Comment by g105b** [comment]
No, you're right. MDN is very clear there with the implementation they expect, so it's good to stick with that, and in reality you will never need to keep reference to the same fragment after it's been attached, so your test seems perfect.

**Comment by g105b** [comment]
I'll see what's wrong with the build/test CI checks. I've been "improving" things with CI today, so must have temporarily broken things.

**Comment by g105b** [comment]
Thanks again @speich and sorry it's taken so long to merge in. Nice to see Github Actions working nicely now.

**Pull request merged**
