### PR TITLE
implement NonDocumentTypeChildNode methods and add tests

### PR DESCRIPTION
**Pull request by speich**

### CODE REVIEW

**Review by g105b — CHANGES_REQUESTED** [review]
Please can you rename the test to a .php file? Other than that, looks perfect.

**Review by g105b — APPROVED** [review]
Great, thanks.

**Comment by g105b** [comment]
Usually I'd keep PRs open for a little while (maybe a couple of days) as I think being too hasty on merging is sometimes a bad quality of open source, but seeing as this isn't merging into master, I'm happy to do it as long as it's well tested.

**Comment by speich** [comment]
Sorry about the noise.

**Comment by g105b** [comment]
No problem. The feature is nicely wrapped up and well tested - that's what matters!

**Pull request merged**
