### PR TITLE
DOM Facade to DOMDocument

### LINKED ISSUE #261: Implement a DOM Facade for true compatibility
In the current version of PHP.Gt/Dom, the objects that are interacted with are extensions of the native DOMDocument objects, but this imposes limitations such as lack of specific element implementation (#260).

If the repository had an overhaul to work as a Facade to the native DOMDocument, full compatibility could be reached, without having to implement an HTML parser and xpath traversal, etc.

Example:

```
$collection = $document->querySelectorAll("table>tr, input");
($collection[0] instanceof HTMLTableRowElement); // true
($collection[1] instanceof HTMLInputElement); //true
```

The querySelectorAll function of the HTMLDocument can map directly to the XPath function of the native DOMDocument element, as it does now, but without being an extension of the Document object - rather, a facade to it.

This will allow the construction of the HTMLCollection above to create the correct object hierarchy, so as each matching item is added to the collection it can check the tagname and create the correct element type.

### PR DESCRIPTION
**Pull request by g105b**
Closes #261

### CODE REVIEW

**Comment by g105b** [comment]
All DOMInterfaces are stubbed (https://developer.mozilla.org/en-US/docs/Web/API/Document_Object_Model#dom_interfaces)

**Comment by g105b** [comment]
Next to implement is the HTML Element Interfaces https://developer.mozilla.org/en-US/docs/Web/API/HTML_DOM_API#html_element_interfaces_2 (specifically for #261 and #260), and then on to SVG interfaces https://developer.mozilla.org/en-US/docs/Web/API/Document_Object_Model#svg_interfaces

**Comment by g105b** [comment]
I've just implemented all the HTMLAudioElement properties - in the process I've introduced a new test helper function: `HTMLElementTestCase::assertPropertyAttributeCorrelateBool()` for asserting that boolean attributes correlate directly to their properties.

**Comment by g105b** [comment]
`HTMLButtonElement` done. Mainly wrapped up in `HTMLUIElement` trait, but these methods must also be tested in the `HTMLInputElement` and others that use it.

**Comment by g105b** [comment]
Hey @speich ,

I've just implemented the other `HTMLTable*Element` classes, I was wondering if you would want to take a look over this while I finish the last bits of implementation?

Let me know what you think!

Greg.

**Comment by g105b** [comment]
Wow, just three more classes to add tests for: 

+ `ChildNode`
+ `DocumentFragment`
+ `Text`

Then it's time to do some integration tests by importing this branch into some live projects!

**Comment by speich** [comment]
I just notices some minor things:

`HTMLTableCellElement.scope`
Specs say:
> Permitted values for scope are: col, colgroup, row, rowgroup, emtpy string

Shouldn't setter throw an error if not?

`HTMLTableColElement.span`
Specs say:
> Must be a positive integer

Shouldn't setter throw an error if not?

`HTMLTableRowElement.deleteCell()`
Why not reuse already existing Exception IndexSizeException? Otherwise replace usage of IndexSizeException in HtmlTableElement and delete IndexSizeException

`HTMLTableRowElement.insertCell()`
Must throw IndexSizeError if index is outside of bounds (or IndexIsNegativeOrGreaterThanAllowedAmountException)
Also handle case when index = -1 (-->same as case null)

`HTMLTableSectionElement.deleteRow()`
IndexSizeException instead?

`HTMLTableSectionElement.insertRow()`
Must throw IndexSizeError if index is outside of bounds (or IndexIsNegativeOrGreaterThanAllowedAmountException)
Also handle case when index = -1 (-->same as case null)

**Comment by g105b** [comment]
Thanks for the feedback @speich ,

> 
>  Specs say:
> 
>     Permitted values for scope are: col, colgroup, row, rowgroup, emtpy string
> 
> Shouldn't setter throw an error if not?

I opted not to, because that's what the browser-based DOM implementation chooses to do. You can set any value to this attribute, so I thought for simplicity's sake it should follow that.

Do you think it would be valuable to throw an exception? I think it would help people out, so I might reconsider.

> 
> HTMLTableColElement.span
> Specs say:
> 
>     Must be a positive integer
> 
> Shouldn't setter throw an error if not?

Same here.

> HTMLTableRowElement.deleteCell()
> Why not reuse already existing Exception IndexSizeException? Otherwise replace usage of IndexSizeException in HtmlTableElement and delete IndexSizeException
> 
> HTMLTableRowElement.insertCell()
> Must throw IndexSizeError if index is outside of bounds (or IndexIsNegativeOrGreaterThanAllowedAmountException)
> Also handle case when index = -1 (-->same as case null)
> 
> HTMLTableSectionElement.deleteRow()
> IndexSizeException instead?
> 
> HTMLTableSectionElement.insertRow()
> Must throw IndexSizeError if index is outside of bounds (or IndexIsNegativeOrGreaterThanAllowedAmountException)
> Also handle case when index = -1 (-->same as case null)

Good catch. I created the new exception to take the browser-derived text, but actually I can reuse the exception you mention, passing the text in the constructor.

Thanks for all of these points. I'll put them into action when I'm next on it.

**Comment by g105b** [comment]
It's been a long while, but 666 commits later and we have a new Facade to the DOM.

The more eyes on this the better. @speich , I'd love to hear your feedback on this.

I'm going to integrate it with some projects of mine that already use DOM heavily, to put it through some real world integration testing, and after a week or so I'll check back here to make a v3 release!

**Comment by speich** [comment]
I'll start a new project for work soon, where I'll be using the new Facade to render jsonstat.org data as HtmlTables. I'm confident it will work out very nicely ! I'll let you know if I come across any problems.

**Comment by j4m3s** [comment]
This is a fantastic step forward.  So natural and obvious.  And a hell of a lot of work to get the code quality and coverage to this level.

1. Why do you use a static factory method (\Gt\Dom\Facade\HTMLDocumentFactory::create) rather than a constructor?
2. I think it's worth adding a section to the readme detailing any known inconsistencies/ gaps between this and the DOM spec.  Even if that section says "No known differences as-of 8 May 2021" it's worth having - it'll give confidence and comfort and aid users in debugging their apps.

**Comment by g105b** [comment]
Thanks @j4m3s. 

1. I made the decision to keep method visibility consistent to the spec, and for some reason all `Node` classes have private constructors throughout the DOM. Take a look in the developer console and type `new HTMLDocument()`...

image

2. That's a good idea. I'll see if I can automate the comparison with the spec in some way, otherwise I'll just leave a message in the "features" section of the readme.

**Comment by j4m3s** [comment]
>     1. I made the decision to keep method visibility consistent to the spec, and for some reason all `Node` classes have private constructors throughout the DOM. Take a look in the developer console and type `new HTMLDocument()`...
> 
> 
> image

Good answer & good logic to keep it that way.  For the sake of completeness in this discussion though... In a browser I'd expect there to be an HTMLDocument already (and only one) - so a constructor wouldn't be sensible.  I assume there also isn't a `::create()` for a new HTMLDocument either, for the same reason?

**Comment by g105b** [comment]
That's a good point. Within WebEngine, the HTMLDocument will already be present, but for developers using DOM outside of the context of WebEngine, I see how this would look like an unnecessary step.

I do agree that it makes sense to keep the `Node`  class's constructor private, because a Node shouldn't be created without the context of a document... but an `HTMLDocument` inherits `Node`, so I'm not sure constructor visibility can be changed in extended objects. I will check this though.

**Comment by g105b** [comment]
The README now has a section dedicated for describing any known limitations. Currently this is limited to any classes that extend the `ClientSideOnly` base class, like `AudioTrackList`, etc.

**Comment by g105b** [comment]
Changing the subject, the following classes should probably be refactored to remove some complexity before merging this PR:

+ Traversal
+ HTMLInputElement
+ HTMLAnchorOrAreaElement
+ HTMLTableElement
+ Node
+ Document

They're all flagged up as too complex in Scrutinizer.

**Comment by g105b** [comment]
Finally merged this to master :tada: 

I've been using this branch in a few applications now, and I can't find any issue with it that hasn't been addressed. I'm going to put together a much more thorough test application before v4 is released, but for now leaving this in `master` is a major step forwards.

Have fun!

**Comment by speich** [comment]
Congrats. Liked working with you.

**Comment by g105b** [comment]
@speich stay in touch! you helped out a lot, I'd be interested in seeing what you've been building with DOM.

**Pull request merged**
