### PR TITLE
Explicit nullable type added with PHP 8.4 support

### PR DESCRIPTION
**Pull request by djadobe16**

### CODE REVIEW

**Comment by glo71317** [comment]
Hi @g105b We have addressed Explicit nullable type added with PHP 8.4 support Can you please review this pr and proceed for merge if all good.

**Comment by g105b** [comment]
Thank you for this. I can foresee a lot of other changes coming with the new features of PHP 8.4, specifically the native DOM functionality, but luckily the new native HTMLDocument class is namespaced so there are no breaking changes.

I noticed that there were a lot of deprecation notices emitted from the new explicit type rules, but I believe the decision for deprecation is a good one, so thank you for implementing this change for PHP 8.4 improvements... I shall get this merged today!

**Comment by djadobe16** [comment]
@g105b Thanks for your response .

**Comment by glo71317** [comment]
@g105b thank you so much for quick response and address this PR. Are we planning to release new version of this package as changes are available in dev-master?

**Comment by g105b** [comment]
I may have to make a simple change to the PR that makes it into the next release, as the typed constants introduce a backwards breaking change (pre PHP 8.3 did not allow typed constants). I'm trying to figure out the best way to do this, so we don't lose this feature (types are always good!), so maybe I'll make two releases, one patch release with backwards compatibility and a new major release that is not backwards compatible.

**Comment by glo71317** [comment]
@g105b Thank you for your response! Is there anything we can do from our side to help make it available sooner?

**Comment by g105b** [comment]
I will complete this today and make the two releases, as it's time for a new release now it's 2025. Have a happy new year, @glo71317 

I have [a sponsorship page](https://github.com/sponsors/g105b), which is completely optional, but I made the new year's resolution to tell more people about it, in case I can begin to make open source development more sustainable for me... check it out if you like, or forward it to your employer... but please don't feel obliged at all.

**Comment by g105b** [comment]
FYI @glo71317 I've made a new release that supports 8.1 through 8.4

Please test and let me know how you get on.

**Comment by glo71317** [comment]
@g105b thank you so much for releasing new version, will test and update you on the same.

**Pull request merged**
